name: Run TrafficSimulatorv2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (e.g., JDK 17, which is commonly used for JavaFX)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # You can use other distributions like 'adopt' or 'zulu'
          java-version: '23'

      # Cache Maven dependencies to speed up the build
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies and build the project
      - name: Build with Maven
        run: mvn clean install

      # Run the JavaFX application (headless mode for CI environments)
      - name: Run JavaFX application
        run: |
          mvn javafx:run
